export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_COLUMN_HEAD_SPECIFICATION = "TOGGLE_COLUMN_HEAD_SPECIFICATION";
export const SHOW_NOTES_FOR = "SHOW_NOTES_FOR";
export const TOGGLE_ACTIONS = "TOGGLE_ACTIONS";
export const CLOSE_ALL_MODALS = "CLOSE_ALL_MODALS";

export const TOGGLE_FILTER_EDITOR = "TOGGLE_FILTER_EDITOR";
export const TOGGLE_COLUMN_SELECTOR_UI = "TOGGLE_COLUMN_SELECTOR_UI";
export const TOGGLE_SORT_EDITOR = "TOGGLE_SORT_EDITOR";

export const COMPLETE_FETCH_APP = "COMPLETE_FETCH_APP";