export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_FILTER_EDITOR = "TOGGLE_FILTER_EDITOR";
export const TOGGLE_COLUMN_HEAD_SPECIFICATION = "TOGGLE_COLUMN_HEAD_SPECIFICATION";
export const SHOW_NOTES_FOR = "SHOW_NOTES_FOR";