export const INITIATE_FETCH_DATA = "INITIATE_FETCH_DATA";
export const COMPLETE_FETCH_DATA = "COMPLETE_FETCH_DATA";
export const LOAD_DATA_FROM_CACHE = "LOAD_DATA_FROM_CACHE";
export const TOGGLE_ROW_SELECTION = "TOGGLE_ROW_SELECTION";