Vagrant.configure(2) do |machine|
  machine.vm.box = "debian/buster64"
  machine.vm.network "private_network", ip: "192.168.77.88"
  machine.vm.synced_folder "../..", "/home/vagrant/dwata", type: "rsync",
    rsync__exclude: ".git/"

  # machine.vm.provision "ansible" do |server|
  #   server.playbook = "playbooks/server.yml"
  # end

  machine.vm.provision "ansible" do |project|
    project.playbook = "playbooks/project.yml"
  end

  machine.vm.provision "ansible" do |server|
    server.playbook = "playbooks/services.yml"
  end
end