// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentSpec } from "../../api_types/ContentSpec";
import type { ContentType } from "../../api_types/ContentType";

export type FormField = { name: string, label: string, description: string | null, placeholder: string | null, contentType: ContentType, contentSpec: ContentSpec, isRequired: boolean | null, isEditable: boolean | null, };