const colors = {
  $schema: "vscode://schemas/color-theme",
  type: "light",
  colors: {
    "activityBar.background": "#ddd6c1",
    "activityBar.foreground": "#584c27",
    "activityBarBadge.background": "#b58900",
    "badge.background": "#b58900aa",
    "button.background": "#ac9d57",
    "debugExceptionWidget.background": "#ddd6c1",
    "debugExceptionWidget.border": "#ab395b",
    "debugToolBar.background": "#ddd6c1",
    "dropdown.background": "#eee8d5",
    "dropdown.border": "#d3af86",
    "editor.background": "#fdf6e3",
    "editor.foreground": "#657b83",
    "editor.lineHighlightBackground": "#eee8d5",
    "editor.selectionBackground": "#eee8d5",
    "editorCursor.foreground": "#657b83",
    "editorGroup.border": "#ddd6c1",
    "editorGroup.dropBackground": "#ddd6c1aa",
    "editorGroupHeader.tabsBackground": "#d9d2c2",
    "editorHoverWidget.background": "#ccc4b0",
    "editorIndentGuide.activeBackground": "#081e2580",
    "editorIndentGuide.background": "#586e7580",
    "editorLineNumber.activeForeground": "#567983",
    "editorWhitespace.foreground": "#586e7580",
    "editorWidget.background": "#eee8d5",
    "extensionButton.prominentBackground": "#b58900",
    "extensionButton.prominentHoverBackground": "#584c27aa",
    focusBorder: "#b49471",
    "input.background": "#ddd6c1",
    "input.foreground": "#586e75",
    "input.placeholderForeground": "#586e75aa",
    "inputOption.activeBorder": "#d3af86",
    "list.activeSelectionBackground": "#dfca88",
    "list.activeSelectionForeground": "#6c6c6c",
    "list.highlightForeground": "#b58900",
    "list.hoverBackground": "#dfca8844",
    "list.inactiveSelectionBackground": "#d1cbb8",
    "minimap.selectionHighlight": "#eee8d5",
    "notebook.cellEditorBackground": "#f7f0e0",
    "panel.border": "#ddd6c1",
    "peekView.border": "#b58900",
    "peekViewEditor.background": "#fffbf2",
    "peekViewEditor.matchHighlightBackground": "#7744aa40",
    "peekViewResult.background": "#eee8d5",
    "peekViewTitle.background": "#eee8d5",
    "pickerGroup.border": "#2aa19899",
    "pickerGroup.foreground": "#2aa19899",
    "ports.iconRunningProcessForeground": "#2aa19899",
    "progressBar.background": "#b58900",
    "quickInputList.focusBackground": "#dfca8866",
    "selection.background": "#878b9180",
    "sideBar.background": "#eee8d5",
    "sideBarTitle.foreground": "#586e75",
    "statusBar.background": "#eee8d5",
    "statusBar.debuggingBackground": "#eee8d5",
    "statusBar.foreground": "#586e75",
    "statusBar.noFolderBackground": "#eee8d5",
    "statusBarItem.prominentBackground": "#ddd6c1",
    "statusBarItem.prominentHoverBackground": "#ddd6c199",
    "statusBarItem.remoteBackground": "#ac9d57",
    "tab.activeBackground": "#fdf6e3",
    "tab.activeModifiedBorder": "#cb4b16",
    "tab.border": "#ddd6c1",
    "tab.inactiveBackground": "#d3cbb7",
    "tab.inactiveForeground": "#586e75",
    "tab.lastPinnedBorder": "#fdf6e3",
    "terminal.ansiBlack": "#073642",
    "terminal.ansiBlue": "#268bd2",
    "terminal.ansiBrightBlack": "#002b36",
    "terminal.ansiBrightBlue": "#839496",
    "terminal.ansiBrightCyan": "#93a1a1",
    "terminal.ansiBrightGreen": "#586e75",
    "terminal.ansiBrightMagenta": "#6c71c4",
    "terminal.ansiBrightRed": "#cb4b16",
    "terminal.ansiBrightWhite": "#fdf6e3",
    "terminal.ansiBrightYellow": "#657b83",
    "terminal.ansiCyan": "#2aa198",
    "terminal.ansiGreen": "#859900",
    "terminal.ansiMagenta": "#d33682",
    "terminal.ansiRed": "#dc322f",
    "terminal.ansiWhite": "#eee8d5",
    "terminal.ansiYellow": "#b58900",
    "terminal.background": "#fdf6e3",
    "titleBar.activeBackground": "#eee8d5",
    "walkThrough.embeddedEditorBackground": "#00000014",
    //"actionBar.toggledBackground": "#b4947133",
    //"activityBar.activeBorder": "#584c27",
    //"activityBar.dropBorder": "#584c27",
    //"activityBar.inactiveForeground": "#584c2766",
    //"activityBarBadge.foreground": "#ffffff",
    //"activityBarTop.activeBorder": "#424242",
    //"activityBarTop.dropBorder": "#424242",
    //"activityBarTop.foreground": "#424242",
    //"activityBarTop.inactiveForeground": "#424242bf",
    //"badge.foreground": "#333333",
    "banner.background": "#c6a435",
    "banner.foreground": "#6c6c6c",
    //"banner.iconForeground": "#1a85ff",
    //"breadcrumb.activeSelectionForeground": "#4e4e4e",
    //"breadcrumb.background": "#fdf6e3",
    //"breadcrumb.focusForeground": "#4e4e4e",
    //"breadcrumb.foreground": "#616161cc",
    //"breadcrumbPicker.background": "#eee8d5",
    //"button.foreground": "#ffffff",
    //"button.hoverBackground": "#8b7e44",
    //"button.secondaryBackground": "#5f6a79",
    //"button.secondaryForeground": "#ffffff",
    //"button.secondaryHoverBackground": "#4c5561",
    //"button.separator": "#ffffff66",
    //"charts.blue": "#1a85ff",
    //"charts.foreground": "#616161",
    //"charts.green": "#388a34",
    //"charts.lines": "#61616180",
    //"charts.orange": "#d18616",
    //"charts.purple": "#652d90",
    //"charts.red": "#e51400",
    //"charts.yellow": "#bf8803",
    //"chat.avatarBackground": "#f2f2f2",
    //"chat.avatarForeground": "#616161",
    //"chat.requestBackground": "#fdf6e39e",
    //"chat.requestBorder": "#0000001a",
    //"chat.slashCommandBackground": "#d2ecff99",
    //"chat.slashCommandForeground": "#306ca2",
    //"checkbox.background": "#eee8d5",
    //"checkbox.border": "#d3af86",
    //"checkbox.foreground": "#616161",
    //"checkbox.selectBackground": "#eee8d5",
    //"checkbox.selectBorder": "#424242",
    //"commandCenter.activeBackground": "#00000014",
    //"commandCenter.activeBorder": "#3333334d",
    //"commandCenter.activeForeground": "#333333",
    //"commandCenter.background": "#0000000d",
    //"commandCenter.border": "#33333333",
    //"commandCenter.debuggingBackground": "#eee8d542",
    //"commandCenter.foreground": "#333333",
    //"commandCenter.inactiveBorder": "#33333326",
    //"commandCenter.inactiveForeground": "#33333399",
    //"commentsView.resolvedIcon": "#61616180",
    //"commentsView.unresolvedIcon": "#b49471",
    //"debugConsole.errorForeground": "#a1260d",
    //"debugConsole.infoForeground": "#1a85ff",
    //"debugConsole.sourceForeground": "#616161",
    //"debugConsole.warningForeground": "#bf8803",
    //"debugConsoleInputIcon.foreground": "#616161",
    //"debugIcon.breakpointCurrentStackframeForeground": "#be8700",
    //"debugIcon.breakpointDisabledForeground": "#848484",
    //"debugIcon.breakpointForeground": "#e51400",
    //"debugIcon.breakpointStackframeForeground": "#89d185",
    //"debugIcon.breakpointUnverifiedForeground": "#848484",
    //"debugIcon.continueForeground": "#007acc",
    //"debugIcon.disconnectForeground": "#a1260d",
    //"debugIcon.pauseForeground": "#007acc",
    //"debugIcon.restartForeground": "#388a34",
    //"debugIcon.startForeground": "#388a34",
    //"debugIcon.stepBackForeground": "#007acc",
    //"debugIcon.stepIntoForeground": "#007acc",
    //"debugIcon.stepOutForeground": "#007acc",
    //"debugIcon.stepOverForeground": "#007acc",
    //"debugIcon.stopForeground": "#a1260d",
    //"debugTokenExpression.boolean": "#0000ff",
    //"debugTokenExpression.error": "#e51400",
    //"debugTokenExpression.name": "#9b46b0",
    //"debugTokenExpression.number": "#098658",
    //"debugTokenExpression.string": "#a31515",
    //"debugTokenExpression.type": "#4a90e2",
    //"debugTokenExpression.value": "#6c6c6ccc",
    //"debugView.exceptionLabelBackground": "#a31515",
    //"debugView.exceptionLabelForeground": "#ffffff",
    //"debugView.stateLabelBackground": "#88888844",
    //"debugView.stateLabelForeground": "#616161",
    //"debugView.valueChangedHighlight": "#569cd6",
    //"descriptionForeground": "#717171",
    //"diffEditor.diagonalFill": "#22222233",
    //"diffEditor.insertedLineBackground": "#9bb95533",
    //"diffEditor.insertedTextBackground": "#9ccc2c40",
    //"diffEditor.move.border": "#8b8b8b9c",
    //"diffEditor.moveActive.border": "#ffa500",
    //"diffEditor.removedLineBackground": "#ff000033",
    //"diffEditor.removedTextBackground": "#ff000033",
    //"diffEditor.unchangedCodeBackground": "#b8b8b829",
    //"diffEditor.unchangedRegionBackground": "#eee8d5",
    //"diffEditor.unchangedRegionForeground": "#616161",
    //"diffEditor.unchangedRegionShadow": "#737373bf",
    //"disabledForeground": "#61616180",
    //"dropdown.foreground": "#616161",
    //"editor.findMatchBackground": "#a8ac94",
    //"editor.findMatchHighlightBackground": "#ea5c0055",
    //"editor.findRangeHighlightBackground": "#b4b4b44d",
    //"editor.focusedStackFrameHighlightBackground": "#cee7ce73",
    //"editor.foldBackground": "#eee8d54d",
    //"editor.foldPlaceholderForeground": "#808080",
    //"editor.hoverHighlightBackground": "#add6ff26",
    //"editor.inactiveSelectionBackground": "#eee8d580",
    //"editor.inlineValuesBackground": "#ffc80033",
    //"editor.inlineValuesForeground": "#00000080",
    //"editor.lineHighlightBorder": "#eeeeee",
    //"editor.linkedEditingBackground": "#ff00004d",
    //"editor.placeholder.foreground": "#00000077",
    //"editor.rangeHighlightBackground": "#fdff0033",
    //"editor.selectionHighlightBackground": "#f3efe199",
    //"editor.snippetFinalTabstopHighlightBorder": "#0a326480",
    //"editor.snippetTabstopHighlightBackground": "#0a326433",
    //"editor.stackFrameHighlightBackground": "#ffff6673",
    //"editor.symbolHighlightBackground": "#ea5c0055",
    //"editor.wordHighlightBackground": "#57575740",
    //"editor.wordHighlightStrongBackground": "#0e639c40",
    //"editor.wordHighlightTextBackground": "#57575740",
    //"editorActiveLineNumber.foreground": "#0b216f",
    //"editorBracketHighlight.foreground1": "#0431fa",
    //"editorBracketHighlight.foreground2": "#319331",
    //"editorBracketHighlight.foreground3": "#7b3814",
    //"editorBracketHighlight.foreground4": "#00000000",
    //"editorBracketHighlight.foreground5": "#00000000",
    //"editorBracketHighlight.foreground6": "#00000000",
    //"editorBracketHighlight.unexpectedBracket.foreground": "#ff1212cc",
    //"editorBracketMatch.background": "#0064001a",
    //"editorBracketMatch.border": "#b9b9b9",
    //"editorBracketPairGuide.activeBackground1": "#00000000",
    //"editorBracketPairGuide.activeBackground2": "#00000000",
    //"editorBracketPairGuide.activeBackground3": "#00000000",
    //"editorBracketPairGuide.activeBackground4": "#00000000",
    //"editorBracketPairGuide.activeBackground5": "#00000000",
    //"editorBracketPairGuide.activeBackground6": "#00000000",
    //"editorBracketPairGuide.background1": "#00000000",
    //"editorBracketPairGuide.background2": "#00000000",
    //"editorBracketPairGuide.background3": "#00000000",
    //"editorBracketPairGuide.background4": "#00000000",
    //"editorBracketPairGuide.background5": "#00000000",
    //"editorBracketPairGuide.background6": "#00000000",
    //"editorCodeLens.foreground": "#919191",
    //"editorCommentsWidget.rangeActiveBackground": "#b494711a",
    //"editorCommentsWidget.rangeBackground": "#b494711a",
    //"editorCommentsWidget.replyInputBackground": "#eee8d5",
    //"editorCommentsWidget.resolvedBorder": "#61616180",
    //"editorCommentsWidget.unresolvedBorder": "#b49471",
    //"editorError.foreground": "#e51400",
    //"editorGhostText.foreground": "#00000077",
    //"editorGroup.dropIntoPromptBackground": "#eee8d5",
    //"editorGroup.dropIntoPromptForeground": "#616161",
    //"editorGroupHeader.noTabsBackground": "#fdf6e3",
    //"editorGutter.addedBackground": "#48985d",
    //"editorGutter.background": "#fdf6e3",
    //"editorGutter.commentGlyphForeground": "#657b83",
    //"editorGutter.commentRangeForeground": "#c9c2ac",
    //"editorGutter.commentUnresolvedGlyphForeground": "#657b83",
    //"editorGutter.deletedBackground": "#e51400",
    //"editorGutter.foldingControlForeground": "#424242",
    //"editorGutter.modifiedBackground": "#2090d3",
    //"editorHint.foreground": "#6c6c6c",
    //"editorHoverWidget.border": "#c8c8c8",
    //"editorHoverWidget.foreground": "#616161",
    //"editorHoverWidget.highlightForeground": "#b58900",
    //"editorHoverWidget.statusBarBackground": "#c5bba5",
    //"editorIndentGuide.activeBackground1": "#081e2580",
    //"editorIndentGuide.activeBackground2": "#00000000",
    //"editorIndentGuide.activeBackground3": "#00000000",
    //"editorIndentGuide.activeBackground4": "#00000000",
    //"editorIndentGuide.activeBackground5": "#00000000",
    //"editorIndentGuide.activeBackground6": "#00000000",
    //"editorIndentGuide.background1": "#586e7580",
    //"editorIndentGuide.background2": "#00000000",
    //"editorIndentGuide.background3": "#00000000",
    //"editorIndentGuide.background4": "#00000000",
    //"editorIndentGuide.background5": "#00000000",
    //"editorIndentGuide.background6": "#00000000",
    //"editorInfo.foreground": "#1a85ff",
    //"editorInlayHint.background": "#b5890011",
    //"editorInlayHint.foreground": "#969696",
    //"editorInlayHint.parameterBackground": "#b5890011",
    //"editorInlayHint.parameterForeground": "#969696",
    //"editorInlayHint.typeBackground": "#b5890011",
    //"editorInlayHint.typeForeground": "#969696",
    //"editorLightBulb.foreground": "#ddb100",
    //"editorLightBulbAi.foreground": "#ddb100",
    //"editorLightBulbAutoFix.foreground": "#007acc",
    //"editorLineNumber.foreground": "#237893",
    //"editorLink.activeForeground": "#0000ff",
    //"editorMarkerNavigation.background": "#fdf6e3",
    //"editorMarkerNavigationError.background": "#e51400",
    //"editorMarkerNavigationError.headerBackground": "#e514001a",
    //"editorMarkerNavigationInfo.background": "#1a85ff",
    //"editorMarkerNavigationInfo.headerBackground": "#1a85ff1a",
    //"editorMarkerNavigationWarning.background": "#bf8803",
    //"editorMarkerNavigationWarning.headerBackground": "#bf88031a",
    //"editorMultiCursor.primary.foreground": "#657b83",
    //"editorMultiCursor.secondary.foreground": "#657b83",
    //"editorOverviewRuler.addedForeground": "#48985d99",
    //"editorOverviewRuler.border": "#7f7f7f4d",
    //"editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
    //"editorOverviewRuler.commentForeground": "#c9c2ac",
    //"editorOverviewRuler.commentUnresolvedForeground": "#c9c2ac",
    //"editorOverviewRuler.commonContentForeground": "#60606066",
    //"editorOverviewRuler.currentContentForeground": "#40c8ae80",
    //"editorOverviewRuler.deletedForeground": "#e5140099",
    //"editorOverviewRuler.errorForeground": "#ff1212b3",
    //"editorOverviewRuler.findMatchForeground": "#d186167e",
    //"editorOverviewRuler.incomingContentForeground": "#40a6ff80",
    //"editorOverviewRuler.infoForeground": "#1a85ff",
    //"editorOverviewRuler.inlineChatInserted": "#9ccc2c33",
    //"editorOverviewRuler.inlineChatRemoved": "#ff000029",
    //"editorOverviewRuler.modifiedForeground": "#2090d399",
    //"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
    //"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.warningForeground": "#bf8803",
    //"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
    //"editorOverviewRuler.wordHighlightTextForeground": "#a0a0a0cc",
    //"editorPane.background": "#fdf6e3",
    //"editorRuler.foreground": "#d3d3d3",
    //"editorStickyScroll.background": "#fdf6e3",
    //"editorStickyScroll.shadow": "#dddddd",
    //"editorStickyScrollHover.background": "#f0f0f0",
    //"editorSuggestWidget.background": "#eee8d5",
    //"editorSuggestWidget.border": "#c8c8c8",
    //"editorSuggestWidget.focusHighlightForeground": "#b58900",
    //"editorSuggestWidget.foreground": "#657b83",
    //"editorSuggestWidget.highlightForeground": "#b58900",
    //"editorSuggestWidget.selectedBackground": "#dfca8866",
    //"editorSuggestWidget.selectedForeground": "#6c6c6c",
    //"editorSuggestWidgetStatus.foreground": "#657b8380",
    //"editorUnicodeHighlight.border": "#bf8803",
    //"editorUnnecessaryCode.opacity": "#00000077",
    //"editorWarning.foreground": "#bf8803",
    //"editorWatermark.foreground": "#657b83ad",
    //"editorWidget.border": "#c8c8c8",
    //"editorWidget.foreground": "#616161",
    //"errorForeground": "#a1260d",
    //"extensionBadge.remoteBackground": "#b58900",
    //"extensionBadge.remoteForeground": "#ffffff",
    //"extensionButton.background": "#ac9d57",
    //"extensionButton.foreground": "#ffffff",
    //"extensionButton.hoverBackground": "#8b7e44",
    //"extensionButton.prominentForeground": "#ffffff",
    //"extensionButton.separator": "#ffffff66",
    //"extensionIcon.preReleaseForeground": "#1d9271",
    //"extensionIcon.sponsorForeground": "#b51e78",
    //"extensionIcon.starForeground": "#df6100",
    //"extensionIcon.verifiedForeground": "#006ab1",
    //"foreground": "#616161",
    //"gitDecoration.addedResourceForeground": "#587c0c",
    //"gitDecoration.conflictingResourceForeground": "#ad0707",
    //"gitDecoration.deletedResourceForeground": "#ad0707",
    //"gitDecoration.ignoredResourceForeground": "#8e8e90",
    //"gitDecoration.modifiedResourceForeground": "#895503",
    //"gitDecoration.renamedResourceForeground": "#007100",
    //"gitDecoration.stageDeletedResourceForeground": "#ad0707",
    //"gitDecoration.stageModifiedResourceForeground": "#895503",
    //"gitDecoration.submoduleResourceForeground": "#1258a7",
    //"gitDecoration.untrackedResourceForeground": "#007100",
    //"icon.foreground": "#424242",
    //"inlineChat.background": "#eee8d5",
    //"inlineChat.border": "#c8c8c8",
    //"inlineChat.foreground": "#616161",
    //"inlineChat.shadow": "#00000029",
    //"inlineChatDiff.inserted": "#9ccc2c20",
    //"inlineChatDiff.removed": "#ff00001a",
    //"inlineChatInput.background": "#ddd6c1",
    //"inlineChatInput.border": "#c8c8c8",
    //"inlineChatInput.focusBorder": "#b49471",
    //"inlineChatInput.placeholderForeground": "#586e75aa",
    //"inputOption.activeBackground": "#b4947133",
    //"inputOption.activeForeground": "#000000",
    //"inputOption.hoverBackground": "#b8b8b850",
    //"inputValidation.errorBackground": "#f2dede",
    //"inputValidation.errorBorder": "#be1100",
    //"inputValidation.infoBackground": "#d6ecf2",
    //"inputValidation.infoBorder": "#007acc",
    //"inputValidation.warningBackground": "#f6f5d2",
    //"inputValidation.warningBorder": "#b89500",
    //"interactive.activeCodeBorder": "#b58900",
    //"interactive.inactiveCodeBorder": "#d1cbb8",
    //"keybindingLabel.background": "#dddddd66",
    //"keybindingLabel.border": "#cccccc66",
    //"keybindingLabel.bottomBorder": "#bbbbbb66",
    //"keybindingLabel.foreground": "#555555",
    //"keybindingTable.headerBackground": "#6161610a",
    //"keybindingTable.rowsBackground": "#6161610a",
    //"list.deemphasizedForeground": "#8e8e90",
    //"list.dropBackground": "#d6ebff",
    //"list.dropBetweenBackground": "#424242",
    //"list.errorForeground": "#b01011",
    //"list.filterMatchBackground": "#ea5c0055",
    //"list.focusHighlightForeground": "#b58900",
    //"list.focusOutline": "#b49471",
    //"list.invalidItemForeground": "#b89500",
    //"list.warningForeground": "#855f00",
    //"listFilterWidget.background": "#eee8d5",
    //"listFilterWidget.noMatchesOutline": "#be1100",
    //"listFilterWidget.outline": "#00000000",
    //"listFilterWidget.shadow": "#00000029",
    //"menu.background": "#eee8d5",
    //"menu.foreground": "#616161",
    //"menu.selectionBackground": "#dfca88",
    //"menu.selectionForeground": "#6c6c6c",
    //"menu.separatorBackground": "#d4d4d4",
    //"menubar.selectionBackground": "#b8b8b850",
    //"menubar.selectionForeground": "#333333",
    //"merge.commonContentBackground": "#60606029",
    //"merge.commonHeaderBackground": "#60606066",
    //"merge.currentContentBackground": "#40c8ae33",
    //"merge.currentHeaderBackground": "#40c8ae80",
    //"merge.incomingContentBackground": "#40a6ff33",
    //"merge.incomingHeaderBackground": "#40a6ff80",
    //"mergeEditor.change.background": "#9bb95533",
    //"mergeEditor.change.word.background": "#9ccc2c66",
    //"mergeEditor.changeBase.background": "#ffcccc",
    //"mergeEditor.changeBase.word.background": "#ffa3a3",
    //"mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
    //"mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
    //"mergeEditor.conflict.handledUnfocused.border": "#86868649",
    //"mergeEditor.conflict.input1.background": "#40c8ae33",
    //"mergeEditor.conflict.input2.background": "#40a6ff33",
    //"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
    //"mergeEditor.conflict.unhandledFocused.border": "#ffa600",
    //"mergeEditor.conflict.unhandledUnfocused.border": "#ffa600",
    //"mergeEditor.conflictingLines.background": "#ffea0047",
    //"minimap.errorHighlight": "#ff1212b3",
    //"minimap.findMatchHighlight": "#d18616",
    //"minimap.foregroundOpacity": "#000000",
    //"minimap.infoHighlight": "#1a85ff",
    //"minimap.selectionOccurrenceHighlight": "#c9c9c9",
    //"minimap.warningHighlight": "#bf8803",
    //"minimapGutter.addedBackground": "#48985d",
    //"minimapGutter.deletedBackground": "#e51400",
    //"minimapGutter.modifiedBackground": "#2090d3",
    //"minimapSlider.activeBackground": "#0000004d",
    //"minimapSlider.background": "#64646433",
    //"minimapSlider.hoverBackground": "#64646459",
    //"multiDiffEditor.border": "#cccccc",
    //"multiDiffEditor.headerBackground": "#d3cbb7",
    //"notebook.cellBorderColor": "#d1cbb8",
    //"notebook.cellInsertionIndicator": "#b49471",
    //"notebook.cellStatusBarItemHoverBackground": "#00000014",
    //"notebook.cellToolbarSeparator": "#80808059",
    //"notebook.editorBackground": "#fdf6e3",
    //"notebook.focusedCellBorder": "#b49471",
    //"notebook.focusedEditorBorder": "#b49471",
    //"notebook.inactiveFocusedCellBorder": "#d1cbb8",
    //"notebook.selectedCellBackground": "#d1cbb8",
    //"notebook.selectedCellBorder": "#d1cbb8",
    //"notebook.symbolHighlightBackground": "#fdff0033",
    //"notebookEditorOverviewRuler.runningCellForeground": "#388a34",
    //"notebookScrollbarSlider.activeBackground": "#00000099",
    //"notebookScrollbarSlider.background": "#64646466",
    //"notebookScrollbarSlider.hoverBackground": "#646464b3",
    //"notebookStatusErrorIcon.foreground": "#a1260d",
    //"notebookStatusRunningIcon.foreground": "#616161",
    //"notebookStatusSuccessIcon.foreground": "#388a34",
    //"notificationCenterHeader.background": "#e7dfc5",
    //"notificationLink.foreground": "#006ab1",
    //"notifications.background": "#eee8d5",
    //"notifications.border": "#e7dfc5",
    //"notifications.foreground": "#616161",
    //"notificationsErrorIcon.foreground": "#e51400",
    //"notificationsInfoIcon.foreground": "#1a85ff",
    //"notificationsWarningIcon.foreground": "#bf8803",
    //"panel.background": "#fdf6e3",
    //"panel.dropBorder": "#424242",
    //"panelInput.border": "#dddddd",
    //"panelSection.border": "#ddd6c1",
    //"panelSection.dropBackground": "#ddd6c1aa",
    //"panelSectionHeader.background": "#80808033",
    //"panelStickyScroll.background": "#fdf6e3",
    //"panelStickyScroll.shadow": "#dddddd",
    //"panelTitle.activeBorder": "#424242",
    //"panelTitle.activeForeground": "#424242",
    //"panelTitle.inactiveForeground": "#424242bf",
    //"peekViewEditorGutter.background": "#fffbf2",
    //"peekViewEditorStickyScroll.background": "#fffbf2",
    //"peekViewResult.fileForeground": "#1e1e1e",
    //"peekViewResult.lineForeground": "#646465",
    //"peekViewResult.matchHighlightBackground": "#ea5c004d",
    //"peekViewResult.selectionBackground": "#3399ff33",
    //"peekViewResult.selectionForeground": "#6c6c6c",
    //"peekViewTitleDescription.foreground": "#616161",
    //"peekViewTitleLabel.foreground": "#000000",
    //"problemsErrorIcon.foreground": "#e51400",
    //"problemsInfoIcon.foreground": "#1a85ff",
    //"problemsWarningIcon.foreground": "#bf8803",
    //"profileBadge.background": "#c4c4c4",
    //"profileBadge.foreground": "#333333",
    //"profiles.sashBorder": "#ddd6c1",
    //"quickInput.background": "#eee8d5",
    //"quickInput.foreground": "#616161",
    //"quickInputList.focusForeground": "#6c6c6c",
    //"quickInputTitle.background": "#0000000f",
    //"radio.activeBackground": "#b4947133",
    //"radio.activeBorder": "#d3af86",
    //"radio.activeForeground": "#000000",
    //"radio.inactiveBorder": "#00000033",
    //"radio.inactiveHoverBackground": "#b8b8b850",
    //"sash.hoverBorder": "#b49471",
    //"scm.historyGraph.green": "#388a34",
    //"scm.historyGraph.historyItemGroupBase": "#d18616",
    //"scm.historyGraph.historyItemGroupHoverLabelForeground": "#ffffff",
    //"scm.historyGraph.historyItemGroupLocal": "#1a85ff",
    //"scm.historyGraph.historyItemGroupRemote": "#652d90",
    //"scm.historyGraph.red": "#e51400",
    //"scm.historyGraph.yellow": "#bf8803",
    //"scm.historyItemAdditionsForeground": "#587c0c",
    //"scm.historyItemDeletionsForeground": "#ad0707",
    //"scm.historyItemSelectedStatisticsBorder": "#6c6c6c33",
    //"scm.historyItemStatisticsBorder": "#61616133",
    //"scrollbar.shadow": "#dddddd",
    //"scrollbarSlider.activeBackground": "#00000099",
    //"scrollbarSlider.background": "#64646466",
    //"scrollbarSlider.hoverBackground": "#646464b3",
    //"search.resultsInfoForeground": "#616161",
    //"searchEditor.findMatchBackground": "#ea5c0038",
    //"settings.checkboxBackground": "#eee8d5",
    //"settings.checkboxBorder": "#d3af86",
    //"settings.checkboxForeground": "#616161",
    //"settings.dropdownBackground": "#eee8d5",
    //"settings.dropdownBorder": "#d3af86",
    //"settings.dropdownForeground": "#616161",
    //"settings.dropdownListBorder": "#c8c8c8",
    //"settings.focusedRowBackground": "#dfca8829",
    //"settings.focusedRowBorder": "#b49471",
    //"settings.headerBorder": "#ddd6c1",
    //"settings.headerForeground": "#444444",
    //"settings.modifiedItemIndicator": "#66afe0",
    //"settings.numberInputBackground": "#ddd6c1",
    //"settings.numberInputForeground": "#586e75",
    //"settings.rowHoverBackground": "#dfca8814",
    //"settings.sashBorder": "#ddd6c1",
    //"settings.settingsHeaderHoverForeground": "#444444b3",
    //"settings.textInputBackground": "#ddd6c1",
    //"settings.textInputForeground": "#586e75",
    //"sideBar.dropBackground": "#ddd6c1aa",
    //"sideBarSectionHeader.background": "#80808033",
    //"sideBarStickyScroll.background": "#eee8d5",
    //"sideBarStickyScroll.shadow": "#dddddd",
    //"sideBarTitle.background": "#eee8d5",
    //"sideBySideEditor.horizontalBorder": "#ddd6c1",
    //"sideBySideEditor.verticalBorder": "#ddd6c1",
    //"simpleFindWidget.sashBorder": "#c8c8c8",
    //"statusBar.debuggingForeground": "#586e75",
    //"statusBar.focusBorder": "#586e75",
    //"statusBar.noFolderForeground": "#586e75",
    //"statusBarItem.activeBackground": "#ffffff2e",
    //"statusBarItem.compactHoverBackground": "#ffffff33",
    //"statusBarItem.errorBackground": "#611708",
    //"statusBarItem.errorForeground": "#ffffff",
    //"statusBarItem.errorHoverBackground": "#ffffff1f",
    //"statusBarItem.errorHoverForeground": "#586e75",
    //"statusBarItem.focusBorder": "#586e75",
    //"statusBarItem.hoverBackground": "#ffffff1f",
    //"statusBarItem.hoverForeground": "#586e75",
    //"statusBarItem.offlineBackground": "#6c1717",
    //"statusBarItem.offlineForeground": "#ffffff",
    //"statusBarItem.offlineHoverBackground": "#ffffff1f",
    //"statusBarItem.offlineHoverForeground": "#586e75",
    //"statusBarItem.prominentForeground": "#586e75",
    //"statusBarItem.prominentHoverForeground": "#586e75",
    //"statusBarItem.remoteForeground": "#ffffff",
    //"statusBarItem.remoteHoverBackground": "#ffffff1f",
    //"statusBarItem.remoteHoverForeground": "#586e75",
    //"statusBarItem.warningBackground": "#725102",
    //"statusBarItem.warningForeground": "#ffffff",
    //"statusBarItem.warningHoverBackground": "#ffffff1f",
    //"statusBarItem.warningHoverForeground": "#586e75",
    //"symbolIcon.arrayForeground": "#616161",
    //"symbolIcon.booleanForeground": "#616161",
    //"symbolIcon.classForeground": "#d67e00",
    //"symbolIcon.colorForeground": "#616161",
    //"symbolIcon.constantForeground": "#616161",
    //"symbolIcon.constructorForeground": "#652d90",
    //"symbolIcon.enumeratorForeground": "#d67e00",
    //"symbolIcon.enumeratorMemberForeground": "#007acc",
    //"symbolIcon.eventForeground": "#d67e00",
    //"symbolIcon.fieldForeground": "#007acc",
    //"symbolIcon.fileForeground": "#616161",
    //"symbolIcon.folderForeground": "#616161",
    //"symbolIcon.functionForeground": "#652d90",
    //"symbolIcon.interfaceForeground": "#007acc",
    //"symbolIcon.keyForeground": "#616161",
    //"symbolIcon.keywordForeground": "#616161",
    //"symbolIcon.methodForeground": "#652d90",
    //"symbolIcon.moduleForeground": "#616161",
    //"symbolIcon.namespaceForeground": "#616161",
    //"symbolIcon.nullForeground": "#616161",
    //"symbolIcon.numberForeground": "#616161",
    //"symbolIcon.objectForeground": "#616161",
    //"symbolIcon.operatorForeground": "#616161",
    //"symbolIcon.packageForeground": "#616161",
    //"symbolIcon.propertyForeground": "#616161",
    //"symbolIcon.referenceForeground": "#616161",
    //"symbolIcon.snippetForeground": "#616161",
    //"symbolIcon.stringForeground": "#616161",
    //"symbolIcon.structForeground": "#616161",
    //"symbolIcon.textForeground": "#616161",
    //"symbolIcon.typeParameterForeground": "#616161",
    //"symbolIcon.unitForeground": "#616161",
    //"symbolIcon.variableForeground": "#007acc",
    //"tab.activeForeground": "#333333",
    //"tab.dragAndDropBorder": "#333333",
    //"tab.inactiveModifiedBorder": "#cb4b1680",
    //"tab.selectedBackground": "#fdf6e3",
    //"tab.selectedForeground": "#333333",
    //"tab.unfocusedActiveBackground": "#fdf6e3",
    //"tab.unfocusedActiveForeground": "#333333b3",
    //"tab.unfocusedActiveModifiedBorder": "#cb4b16b3",
    //"tab.unfocusedInactiveBackground": "#d3cbb7",
    //"tab.unfocusedInactiveForeground": "#586e7580",
    //"tab.unfocusedInactiveModifiedBorder": "#cb4b1640",
    //"terminal.border": "#ddd6c1",
    //"terminal.dropBackground": "#ddd6c1aa",
    //"terminal.findMatchBackground": "#a8ac94",
    //"terminal.findMatchHighlightBackground": "#ea5c0055",
    //"terminal.foreground": "#333333",
    //"terminal.hoverHighlightBackground": "#add6ff13",
    //"terminal.inactiveSelectionBackground": "#eee8d580",
    //"terminal.initialHintForeground": "#00000077",
    //"terminal.selectionBackground": "#eee8d5",
    //"terminalCommandDecoration.defaultBackground": "#00000040",
    //"terminalCommandDecoration.errorBackground": "#e51400",
    //"terminalCommandDecoration.successBackground": "#2090d3",
    //"terminalOverviewRuler.border": "#7f7f7f4d",
    //"terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
    //"terminalOverviewRuler.findMatchForeground": "#d186167e",
    //"terminalStickyScrollHover.background": "#f0f0f0",
    //"testing.coverCountBadgeBackground": "#b58900aa",
    //"testing.coverCountBadgeForeground": "#333333",
    //"testing.coveredBackground": "#9ccc2c40",
    //"testing.coveredBorder": "#9ccc2c30",
    //"testing.coveredGutterBackground": "#9ccc2c27",
    //"testing.iconErrored": "#f14c4c",
    //"testing.iconErrored.retired": "#f14c4cb3",
    //"testing.iconFailed": "#f14c4c",
    //"testing.iconFailed.retired": "#f14c4cb3",
    //"testing.iconPassed": "#73c991",
    //"testing.iconPassed.retired": "#73c991b3",
    //"testing.iconQueued": "#cca700",
    //"testing.iconQueued.retired": "#cca700b3",
    //"testing.iconSkipped": "#848484",
    //"testing.iconSkipped.retired": "#848484b3",
    //"testing.iconUnset": "#848484",
    //"testing.iconUnset.retired": "#848484b3",
    //"testing.message.error.decorationForeground": "#e51400",
    //"testing.message.error.lineBackground": "#ff000033",
    //"testing.message.info.decorationForeground": "#657b8380",
    //"testing.messagePeekBorder": "#1a85ff",
    //"testing.messagePeekHeaderBackground": "#1a85ff1a",
    //"testing.peekBorder": "#e51400",
    //"testing.peekHeaderBackground": "#e514001a",
    //"testing.runAction": "#73c991",
    //"testing.uncoveredBackground": "#ff000033",
    //"testing.uncoveredBorder": "#ff000026",
    //"testing.uncoveredBranchBackground": "#fd9388",
    //"testing.uncoveredGutterBackground": "#ff00004d",
    //"textBlockQuote.background": "#f2f2f2",
    //"textBlockQuote.border": "#007acc80",
    //"textCodeBlock.background": "#dcdcdc66",
    //"textLink.activeForeground": "#006ab1",
    //"textLink.foreground": "#006ab1",
    //"textPreformat.background": "#0000001a",
    //"textPreformat.foreground": "#a31515",
    //"textSeparator.foreground": "#0000002e",
    //"titleBar.activeForeground": "#333333",
    //"titleBar.inactiveBackground": "#eee8d599",
    //"titleBar.inactiveForeground": "#33333399",
    //"toolbar.activeBackground": "#a6a6a650",
    //"toolbar.hoverBackground": "#b8b8b850",
    //"tree.inactiveIndentGuidesStroke": "#a9a9a966",
    //"tree.indentGuidesStroke": "#a9a9a9",
    //"tree.tableColumnsBorder": "#61616120",
    //"tree.tableOddRowsBackground": "#6161610a",
    //"walkthrough.stepTitle.foreground": "#000000",
    //"welcomePage.progress.background": "#ddd6c1",
    //"welcomePage.progress.foreground": "#006ab1",
    //"welcomePage.tileBackground": "#eee8d5",
    //"welcomePage.tileBorder": "#0000001a",
    //"welcomePage.tileHoverBackground": "#e1d7b5",
    //"widget.shadow": "#00000029",
    //"activityBar.activeBackground": null,
    //"activityBar.activeFocusBorder": null,
    //"activityBar.border": null,
    //"activityBarTop.activeBackground": null,
    //"activityBarTop.background": null,
    //"button.border": null,
    //"contrastActiveBorder": null,
    //"contrastBorder": null,
    //"debugToolBar.border": null,
    //"diffEditor.border": null,
    //"diffEditor.insertedTextBorder": null,
    //"diffEditor.removedTextBorder": null,
    //"diffEditorGutter.insertedLineBackground": null,
    //"diffEditorGutter.removedLineBackground": null,
    //"diffEditorOverview.insertedForeground": null,
    //"diffEditorOverview.removedForeground": null,
    //"dropdown.listBackground": null,
    //"editor.findMatchBorder": null,
    //"editor.findMatchForeground": null,
    //"editor.findMatchHighlightBorder": null,
    //"editor.findMatchHighlightForeground": null,
    //"editor.findRangeHighlightBorder": null,
    //"editor.rangeHighlightBorder": null,
    //"editor.selectionForeground": null,
    //"editor.selectionHighlightBorder": null,
    //"editor.snippetFinalTabstopHighlightBackground": null,
    //"editor.snippetTabstopHighlightBorder": null,
    //"editor.symbolHighlightBorder": null,
    //"editor.wordHighlightBorder": null,
    //"editor.wordHighlightStrongBorder": null,
    //"editor.wordHighlightTextBorder": null,
    //"editorCursor.background": null,
    //"editorError.background": null,
    //"editorError.border": null,
    //"editorGhostText.background": null,
    //"editorGhostText.border": null,
    //"editorGroup.dropIntoPromptBorder": null,
    //"editorGroup.emptyBackground": null,
    //"editorGroup.focusedEmptyBorder": null,
    //"editorGroupHeader.border": null,
    //"editorGroupHeader.tabsBorder": null,
    //"editorHint.border": null,
    //"editorInfo.background": null,
    //"editorInfo.border": null,
    //"editorLineNumber.dimmedForeground": null,
    //"editorMultiCursor.primary.background": null,
    //"editorMultiCursor.secondary.background": null,
    //"editorOverviewRuler.background": null,
    //"editorStickyScroll.border": null,
    //"editorSuggestWidget.selectedIconForeground": null,
    //"editorUnicodeHighlight.background": null,
    //"editorUnnecessaryCode.border": null,
    //"editorWarning.background": null,
    //"editorWarning.border": null,
    //"editorWidget.resizeBorder": null,
    //"input.border": null,
    //"inputValidation.errorForeground": null,
    //"inputValidation.infoForeground": null,
    //"inputValidation.warningForeground": null,
    //"list.activeSelectionIconForeground": null,
    //"list.filterMatchBorder": null,
    //"list.focusAndSelectionOutline": null,
    //"list.focusBackground": null,
    //"list.focusForeground": null,
    //"list.hoverForeground": null,
    //"list.inactiveFocusBackground": null,
    //"list.inactiveFocusOutline": null,
    //"list.inactiveSelectionForeground": null,
    //"list.inactiveSelectionIconForeground": null,
    //"menu.border": null,
    //"menu.selectionBorder": null,
    //"menubar.selectionBorder": null,
    //"merge.border": null,
    //"minimap.background": null,
    //"multiDiffEditor.background": null,
    //"notebook.cellHoverBackground": null,
    //"notebook.focusedCellBackground": null,
    //"notebook.inactiveSelectedCellBorder": null,
    //"notebook.outputContainerBackgroundColor": null,
    //"notebook.outputContainerBorderColor": null,
    //"notificationCenter.border": null,
    //"notificationCenterHeader.foreground": null,
    //"notificationToast.border": null,
    //"outputView.background": null,
    //"outputViewStickyScroll.background": null,
    //"panelSectionHeader.border": null,
    //"panelSectionHeader.foreground": null,
    //"panelStickyScroll.border": null,
    //"peekViewEditor.matchHighlightBorder": null,
    //"quickInput.list.focusBackground": null,
    //"quickInputList.focusIconForeground": null,
    //"radio.inactiveBackground": null,
    //"radio.inactiveForeground": null,
    //"searchEditor.findMatchBorder": null,
    //"searchEditor.textInputBorder": null,
    //"settings.numberInputBorder": null,
    //"settings.textInputBorder": null,
    //"sideBar.border": null,
    //"sideBar.foreground": null,
    //"sideBarActivityBarTop.border": null,
    //"sideBarSectionHeader.border": null,
    //"sideBarSectionHeader.foreground": null,
    //"sideBarStickyScroll.border": null,
    //"statusBar.border": null,
    //"statusBar.debuggingBorder": null,
    //"statusBar.noFolderBorder": null,
    //"tab.activeBorder": null,
    //"tab.activeBorderTop": null,
    //"tab.hoverBackground": null,
    //"tab.hoverBorder": null,
    //"tab.hoverForeground": null,
    //"tab.selectedBorderTop": null,
    //"tab.unfocusedActiveBorder": null,
    //"tab.unfocusedActiveBorderTop": null,
    //"tab.unfocusedHoverBackground": null,
    //"tab.unfocusedHoverBorder": null,
    //"tab.unfocusedHoverForeground": null,
    //"terminal.findMatchBorder": null,
    //"terminal.findMatchHighlightBorder": null,
    //"terminal.selectionForeground": null,
    //"terminal.tab.activeBorder": null,
    //"terminalCursor.background": null,
    //"terminalCursor.foreground": null,
    //"terminalStickyScroll.background": null,
    //"terminalStickyScroll.border": null,
    //"testing.message.info.lineBackground": null,
    //"titleBar.border": null,
    //"toolbar.hoverOutline": null,
    //"welcomePage.background": null,
    //"widget.border": null,
    //"window.activeBorder": null,
    //"window.inactiveBorder": null
  },
  tokenColors: [
    {
      scope: [
        "meta.embedded",
        "source.groovy.embedded",
        "string meta.image.inline.markdown",
        "variable.legacy.builtin.python",
      ],
      settings: {
        foreground: "#657B83",
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: "#93A1A1",
        fontStyle: "italic",
      },
    },
    {
      scope: "string",
      settings: {
        foreground: "#2AA198",
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: "#DC322F",
      },
    },
    {
      scope: "constant.numeric",
      settings: {
        foreground: "#D33682",
      },
    },
    {
      scope: ["variable.language", "variable.other"],
      settings: {
        foreground: "#268BD2",
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: "#859900",
      },
    },
    {
      scope: "storage",
      settings: {
        foreground: "#586E75",
        fontStyle: "bold",
      },
    },
    {
      scope: [
        "entity.name.class",
        "entity.name.type",
        "entity.name.namespace",
        "entity.name.scope-resolution",
      ],
      settings: {
        foreground: "#CB4B16",
        fontStyle: "",
      },
    },
    {
      scope: "entity.name.function",
      settings: {
        foreground: "#268BD2",
      },
    },
    {
      scope: "punctuation.definition.variable",
      settings: {
        foreground: "#859900",
      },
    },
    {
      scope: [
        "punctuation.section.embedded.begin",
        "punctuation.section.embedded.end",
      ],
      settings: {
        foreground: "#DC322F",
      },
    },
    {
      scope: ["constant.language", "meta.preprocessor"],
      settings: {
        foreground: "#B58900",
      },
    },
    {
      scope: ["support.function.construct", "keyword.other.new"],
      settings: {
        foreground: "#CB4B16",
      },
    },
    {
      scope: ["constant.character", "constant.other"],
      settings: {
        foreground: "#CB4B16",
      },
    },
    {
      scope: "entity.other.inherited-class",
      settings: {
        foreground: "#6C71C4",
      },
    },
    {
      scope: "variable.parameter",
      settings: {},
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: "#268BD2",
      },
    },
    {
      scope: "punctuation.definition.tag",
      settings: {
        foreground: "#93A1A1",
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: "#93A1A1",
      },
    },
    {
      scope: "support.function",
      settings: {
        foreground: "#268BD2",
      },
    },
    {
      scope: "punctuation.separator.continuation",
      settings: {
        foreground: "#DC322F",
      },
    },
    {
      scope: ["support.constant", "support.variable"],
      settings: {},
    },
    {
      scope: ["support.type", "support.class"],
      settings: {
        foreground: "#859900",
      },
    },
    {
      scope: "support.type.exception",
      settings: {
        foreground: "#CB4B16",
      },
    },
    {
      scope: "support.other.variable",
      settings: {},
    },
    {
      scope: "invalid",
      settings: {
        foreground: "#DC322F",
      },
    },
    {
      scope: ["meta.diff", "meta.diff.header"],
      settings: {
        foreground: "#268BD2",
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.deleted",
      settings: {
        foreground: "#DC322F",
        fontStyle: "",
      },
    },
    {
      scope: "markup.changed",
      settings: {
        foreground: "#CB4B16",
        fontStyle: "",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: "#859900",
      },
    },
    {
      scope: "markup.quote",
      settings: {
        foreground: "#859900",
      },
    },
    {
      scope: "markup.list",
      settings: {
        foreground: "#B58900",
      },
    },
    {
      scope: ["markup.bold", "markup.italic"],
      settings: {
        foreground: "#D33682",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.strikethrough",
      settings: {
        fontStyle: "strikethrough",
      },
    },
    {
      scope: "markup.inline.raw",
      settings: {
        foreground: "#2AA198",
        fontStyle: "",
      },
    },
    {
      scope: "markup.heading",
      settings: {
        foreground: "#268BD2",
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.heading.setext",
      settings: {
        foreground: "#268BD2",
        fontStyle: "",
      },
    },
    {
      scope: "token.info-token",
      settings: {
        foreground: "#316BCD",
      },
    },
    {
      scope: "token.warn-token",
      settings: {
        foreground: "#CD9731",
      },
    },
    {
      scope: "token.error-token",
      settings: {
        foreground: "#CD3131",
      },
    },
    {
      scope: "token.debug-token",
      settings: {
        foreground: "#800080",
      },
    },
  ],
};

const getColors = () => {
  return colors;
};

export default getColors;
