// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DirectorySource = { id: bigint, path: string, label: string | null, includePatterns: Vec<String>, excludePatterns: Vec<String>, createdAt: string, modifiedAt: string | null, };