export const ADD_ORDER = "ADD_ORDER";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const TOGGLE_ORDER = "TOGGLE_ORDER";  // Uses from table header

export const TOGGLE_QUERY_EDITOR = "TOGGLE_QUERY_EDITOR";
export const TOGGLE_COLUMN_SELECTOR_UI = "TOGGLE_COLUMN_SELECTOR_UI";
export const TOGGLE_SORT_EDITOR = "TOGGLE_SORT_EDITOR";

export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const CHANGE_PER_PAGE = "CHANGE_PER_PAGE";

export const TOGGLE_COLUMN_SELECTION = "TOGGLE_COLUMN_SELECTION";