// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIProvider } from "./AIProvider";

export interface AIIntegration {
  id: bigint;
  aiProvider: AIProvider;
  apiKey: string | null;
  displayLabel: string | null;
}
