// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AIIntegrationCreateUpdate {
  label: string | null;
  aiProvider: string | null;
  apiKey: string | null;
}
