// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AIIntegrationCreateUpdate {
  aiProvider: string | null;
  apiKey: string | null;
  displayLabel: string | null;
  createdAt: string;
}
