// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIAIModel { apiName: string, label: string, contextWindow: number | null, }