// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIAPIntegration {
  id: string;
  aiProvider: string;
  displayLabel: string | null;
}
