// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIAIModel } from "./APIAIModel";

export interface APIAIProvider { name: string, aiModelList: Array<APIAIModel>, }