// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIDataSource } from "./APIDataSource";

export interface APIConfig {
  dataSourceList: Array<APIDataSource>;
}
