// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIChatContextType } from "./APIChatContextType";

export interface APIChatContextNode { id: string, contextType: APIChatContextType, contextLabel: string, canCreateContext: boolean, }