// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIChatReply {
  id: bigint;
  message: string;
  chatThreadId: bigint;
  createdById: bigint;
  createdAt: string;
}
