// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIChatThread {
  id: bigint;
  title: string;
  summary: string | null;
  labels: Array<string>;
  aiProvider: string;
  aiModel: string;
  createdById: bigint;
  createdAt: string;
}
