// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIAIIntegration } from "./APIAIIntegration";
import type { APIDataSource } from "./APIDataSource";
import type { APIFolderSource } from "./APIFolderSource";

export interface APIConfig {
  dataSourceList: Array<APIDataSource>;
  folderList: Array<APIFolderSource>;
  aiIntegrationList: Array<APIAIIntegration>;
}
