// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIDataSource {
  id: string;
  label: string | null;
  sourceType: string;
  sourceName: string;
}
