// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIContentCode } from "./APIContentCode";
import type { APIContentImage } from "./APIContentImage";
import type { APIContentLink } from "./APIContentLink";

export type APIFileContent =
  | { heading: string }
  | { paragraph: string }
  | { image: APIContentImage }
  | { link: APIContentLink }
  | { bulletlist: Array<string> }
  | { code: APIContentCode };
