// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIFileContent } from "./APIFileContent";

export interface APIFileNode {
  relativePath: string;
  isFolder: boolean;
  contents: Array<[number, APIFileContent]>;
}
