// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface APIGridData {
  source: string;
  schema: string | null;
  table: string | null;
  rows: Array<Array<string>>;
}
