// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIGridColumn } from "./APIGridColumn";

export interface APIGridSchema {
  source: string;
  name: string | null;
  schema: string | null;
  columns: Array<APIGridColumn>;
  primaryKey: string | null;
  foreignKeys: Array<string>;
  comment: string | null;
  hasFetchedColumns: boolean;
}
