// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIQueryOrder } from "./APIQueryOrder";

export interface APIGridQuery {
  source: string;
  schema: string | null;
  table: string | null;
  columns: Array<string>;
  ordering: Record<number, APIQueryOrder> | null;
  filtering: Record<number, string> | null;
}
