// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export interface BackgroundTask {
  id: bigint;
  name: string;
  status: TaskStatus;
}
