// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatFilters = {
  role: string | null;
  rootChatId: number;
  rootChatNull: boolean | null;
  requestedAiModel: string | null;
};
