// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessStatus } from "./ProcessStatus";
import type { Role } from "./Role";

export type Chat = {
  id: number;
  rootChatId: number;
  role: Role | null;
  message: string | null;
  requestedAiModel: string | null;
  processStatus: ProcessStatus | null;
  createdById: bigint | null;
  createdAt: string;
};
