// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export interface Chat {
  id: number;
  rootChatId: bigint | null;
  role: Role | null;
  message: string | null;
  toolResponse: Vec<ChatToolResponse>;
  isSystemChat: boolean;
  requestedAiModel: string | null;
  isProcessedByAi: boolean | null;
  apiErrorResponse: string | null;
  createdById: bigint | null;
  createdAt: string;
}
