// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatToolResponse } from "./ChatToolResponse";

export interface ChatCreateUpdate {
  role: string | null;
  rootChatId: bigint | null;
  message: string | null;
  requestedAiModel: string | null;
  toolResponse: Array<ChatToolResponse> | null;
  isProcessedByAi: boolean | null;
}
