// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentFormat } from "./ContentFormat";

export interface Chat {
  id: bigint;
  previousChatId: bigint | null;
  message: string | null;
  requestedContentFormat: ContentFormat | null;
  toolResponse: Vec<ChatToolResponse>;
  isSystemChat: boolean;
  requestedAiModelId: bigint | null;
  isProcessedByAi: boolean | null;
  apiErrorResponse: string | null;
  createdById: bigint | null;
  createdAt: string;
}
