// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormField } from "./FormField";

export type Configuration = {
  title: string;
  description: string;
  fields: Array<FormField>;
};
