// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormFieldData } from "./FormFieldData";

export interface ConfigurationData {
  id: string | null;
  data: Array<FormFieldData>;
}
