// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormField } from "./FormField";

export interface Configuration {
  name: string;
  description: string;
  fields: Array<FormField>;
}
