// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSource } from "./DataSource";

export interface Config {
  dataSourceList: Array<DataSource>;
}
