// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contact = {
  id: bigint;
  firstName: string | null;
  lastName: string | null;
  emailAddressList: Array<string>;
  createdAt: string;
  modifiedAt: string | null;
};
