// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contact = {
  id: bigint;
  firstName: string;
  lastName: string | null;
  emails: Array<string>;
  phoneNumbers: Array<string>;
  organizationId: bigint | null;
  createdAt: string;
  modifiedAt: string | null;
};
