// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentType =
  | "Text"
  | "TextArray"
  | "SingleChoice"
  | "Image"
  | "Link"
  | "Code"
  | "FilePath"
  | "DateTime";
