// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextType } from "./TextType";

export interface ContentSpec {
  textType: TextType | null;
  lengthLimits: [number, number] | null;
  choicesWithStringKeys: Array<[string, string]> | null;
  isPrompt: boolean | null;
}
