// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSourceType } from "./DataSourceType";

export interface DataSource {
  id: string;
  label: string | null;
  source: DataSourceType;
}
