// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Database } from "./Database";

export type DataSourceType =
  | { postgresql: Database }
  | { mysql: Database }
  | { sqlite: Database }
  | { mssql: Database }
  | { mongodb: Database };
