// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DatabaseSourceCreateUpdate {
  label: string | null;
  databaseType: string | null;
  databaseName: string | null;
  databaseHost: string | null;
  databasePort: number | null;
  databaseUsername: string | null;
  databasePassword: string | null;
}
