// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseType } from "./DatabaseType";

export type DatabaseSource = {
  id: bigint;
  label: string | null;
  databaseType: DatabaseType;
  databaseName: string | null;
  pathToLocalDatabase: string | null;
  databaseHost: string | null;
  databasePort: number | null;
  databaseUsername: string | null;
  databasePassword: string | null;
  databaseApiKey: string | null;
  sshHost: string | null;
  sshPort: number | null;
  sshUsername: string | null;
  sshPassword: string | null;
  sshKeyPath: string | null;
  createdAt: string;
  modifiedAt: string | null;
};
