// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailBucket = {
  id: number;
  rootEmailUid: number;
  uidList: Array<number>;
  summary: string | null;
  areInAThread: boolean | null;
  areSimilar: boolean | null;
};
