// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailAccountCreateUpdate = {
  provider: string | null;
  emailAddress: string | null;
  password: string | null;
  oauth2AppId: bigint | null;
};
