// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Email = {
  uid: number;
  mailboxId: number;
  fromName: string;
  fromEmail: string;
  date: bigint;
  subject: string;
  messageId: string | null;
  inReplyTo: string | null;
};
