// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Email = {
  from: [string, string];
  date: string;
  subject: string;
  bodyText: string;
};
