// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailProvider } from "./EmailProvider";

export type EmailAccount = {
  id: number;
  provider: EmailProvider;
  emailAddress: string;
  password: string | null;
  oauth2TokenId: bigint | null;
  createdAt: string;
  modifiedAt: string | null;
};
