// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeterogeneousContentArray } from "./HeterogeneousContentArray";

export interface File {
  relativePath: string;
  isDirectory: boolean;
  contents: Array<HeterogeneousContentArray>;
}
