// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./Content";

export type FormFieldData = { Single: Content } | { Array: Array<Content> };
