// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Label = {
  id: bigint;
  displayName: string;
  parentId: bigint | null;
  isSuggested: boolean;
  createdAt: string;
  modifiedAt: string | null;
};
