// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Mailbox = {
  id: number;
  emailAccountId: number;
  name: string;
  messages: number | null;
  uidNext: number | null;
  uidValidity: number | null;
};
