// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Directory } from "./Directory";
import type { UserAccount } from "./UserAccount";

export type ModuleDataRead =
  | { UserAccount: UserAccount }
  | { Directory: Directory };
