// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleDataList } from "./ModuleDataList";

export type ModuleDataReadList = {
  totalItems: number;
  limit: number;
  offset: number;
  data: ModuleDataList;
};
