// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIIntegration } from "./AIIntegration";
import type { DatabaseSource } from "./DatabaseSource";
import type { DirectorySource } from "./DirectorySource";
import type { UserAccount } from "./UserAccount";

export type ModuleDataReadList =
  | { UserAccount: Array<UserAccount> }
  | { DirectorySource: Array<DirectorySource> }
  | { DatabaseSource: Array<DatabaseSource> }
  | { AIIntegration: Array<AIIntegration> };
