// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectoryCreateUpdate } from "./DirectoryCreateUpdate";
import type { UserAccountCreateUpdate } from "./UserAccountCreateUpdate";

export type ModuleDataCreateUpdate =
  | { UserAccount: UserAccountCreateUpdate }
  | { Directory: DirectoryCreateUpdate };
