// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIIntegration } from "./AIIntegration";
import type { Chat } from "./Chat";
import type { DatabaseSource } from "./DatabaseSource";
import type { DirectorySource } from "./DirectorySource";
import type { Email } from "./Email";
import type { EmailAccount } from "./EmailAccount";
import type { Mailbox } from "./Mailbox";
import type { OAuth2App } from "./OAuth2App";
import type { UserAccount } from "./UserAccount";

export type ModuleDataRead =
  | { type: "UserAccount"; data: UserAccount }
  | { type: "DirectorySource"; data: DirectorySource }
  | { type: "DatabaseSource"; data: DatabaseSource }
  | { type: "AIIntegration"; data: AIIntegration }
  | { type: "Chat"; data: Chat }
  | { type: "OAuth2App"; data: OAuth2App }
  | { type: "EmailAccount"; data: EmailAccount }
  | { type: "Mailbox"; data: Mailbox }
  | { type: "Email"; data: Email };
