// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIIntegrationCreateUpdate } from "./AIIntegrationCreateUpdate";
import type { ChatCreateUpdate } from "./ChatCreateUpdate";
import type { DatabaseSourceCreateUpdate } from "./DatabaseSourceCreateUpdate";
import type { DirectorySourceCreateUpdate } from "./DirectorySourceCreateUpdate";
import type { EmailAccountCreateUpdate } from "./EmailAccountCreateUpdate";
import type { OAuth2CreateUpdate } from "./OAuth2CreateUpdate";
import type { UserAccountCreateUpdate } from "./UserAccountCreateUpdate";

export type ModuleDataCreateUpdate =
  | { UserAccount: UserAccountCreateUpdate }
  | { DirectorySource: DirectorySourceCreateUpdate }
  | { DatabaseSource: DatabaseSourceCreateUpdate }
  | { AIIntegration: AIIntegrationCreateUpdate }
  | { Chat: ChatCreateUpdate }
  | { OAuth2: OAuth2CreateUpdate }
  | { EmailAccount: EmailAccountCreateUpdate };
