// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Configuration } from "./Configuration";

export type NextStep =
  | { type: "Configure"; data: Configuration }
  | { type: "Continue" };
