// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuth2Provider } from "./OAuth2Provider";

export type OAuth2 = {
  id: number;
  provider: OAuth2Provider;
  clientId: string;
  clientSecret: string | null;
  authorizationCode: string;
  accessToken: string;
  refreshToken: string | null;
  identifier: string;
  handle: string | null;
  createdAt: string;
  modifiedAt: string | null;
};
