// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuth2CreateUpdate = {
  provider: string | null;
  clientId: string | null;
  clientSecret: string | null;
};
