// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuth2Token = {
  id: number;
  oauth2AppId: bigint;
  authorizationCode: string;
  accessToken: string;
  refreshToken: string | null;
  identifier: string;
  handle: string | null;
  createdAt: string;
  modifiedAt: string | null;
};
