// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Objective = {
  id: bigint;
  item: string;
  isComplete: boolean;
  order: bigint;
};
