// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessStatus =
  | "not_applicable"
  | "request_sent"
  | "response_received"
  | "error_received";
