// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInLog } from "./ProcessInLog";
import type { ProcessingStatusInLog } from "./ProcessingStatusInLog";

export type ProcessLog = {
  id: number;
  task: ProcessInLog;
  arguments: Array<[string, string]>;
  status: ProcessingStatusInLog;
  isSentToFrontend: boolean;
  createdAt: string;
  modifiedAt: string | null;
};
