// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchableEmail = {
  id: string;
  accountId: bigint;
  mailbox: string;
  fromName: string;
  fromEmail: string;
  date: bigint;
  subject: string;
  bodyText: string;
};
