// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchCollection } from "./SearchCollection";

export type SearchResult = { found: number; hits: Array<SearchCollection> };
