// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchableEmail } from "./SearchableEmail";

export type TypesenseSearchResultHit = { document: SearchableEmail };
