// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserAccount {
  id: bigint;
  firstName: string;
  lastName: string | null;
  email: string | null;
  isSystemUser: boolean | null;
  createdAt: string;
}
