// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from "./Step";

export interface Workflow {
  id: bigint;
  title: string | null;
  summary: string | null;
  systemPrompt: string | null;
  aiModelId: bigint | null;
  objectiveList: Vec<Objective>;
  stepList: Array<Step>;
  createdAt: string;
}
