// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Objective } from "./Objective";
import type { Step } from "./Step";

export type Workflow = {
  id: bigint;
  title: string | null;
  summary: string | null;
  systemPrompt: string | null;
  aiModelId: bigint | null;
  objectiveList: Array<Objective>;
  stepList: Array<Step>;
  createdAt: string;
};
