// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeArray } from "./TypeArray";
import type { TypeFloat } from "./TypeFloat";
import type { TypeInteger } from "./TypeInteger";

export type ColumnDataType =
  | { signedinteger: TypeInteger }
  | { float: TypeFloat }
  | { chararray: TypeArray }
  | "boolean"
  | "json"
  | "jsonb"
  | "uuid"
  | "text"
  | "unknown";
