// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ColumnPath {
  columnName: string;
  tableName: string;
  dataSourceId: string;
}
