// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnPath } from "./ColumnPath";

export interface Data {
  columns: Array<ColumnPath>;
  rows: Array<Array<string>>;
}
