// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnPath } from "./ColumnPath";

export interface DwataData {
  columns: Array<ColumnPath>;
  rowsOfColumns: Array<Array<string>>;
}
