// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDataSourceType } from "./IDataSourceType";

export interface IDataSource {
  id: string;
  label: string | null;
  source: IDataSourceType;
}
