// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IDatabase } from "./IDatabase";

export type IDataSourceType =
  | { postgresql: IDatabase }
  | { mysql: IDatabase }
  | { sqlite: IDatabase }
  | { mssql: IDatabase }
  | { mongodb: IDatabase };
