// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Data } from "./Data";
import type { Query } from "./Query";

export interface QueryAndData {
  query: Query;
  data: Data;
  errors: Array<string>;
}
