// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnPath } from "./ColumnPath";
import type { QueryOrder } from "./QueryOrder";

export interface Query {
  select: Array<ColumnPath>;
  ordering: Record<number, QueryOrder> | null;
  filtering: Record<number, string> | null;
}
