pub static DATA_SOURCES: &str = r#"
"id","label","path"
1,"products","products"
2,"orders","orders"
3,"line_items","line_items"
4,"shipments","shipments"
10,"users","users"
11,"carts","carts"
20,"cart_items","cart_items"
"#;

pub static LABELS: &str = r#"
"id","label","path"
1,"sales","sales"
2,"support","support"
3,"engineering","engineering"
4,"marketing","marketing"
5,"product","product"
6,"shipping","shipping"
"#;
pub static DATA_PRODUCTS: &str = r#"
"id","name","price","description","category","image_url"
1,"Apple iPhone 11 Pro Max","1099.00","The iPhone 11 Pro Max is the largest and most powerful phone Apple’s ever created, taking the very best of its technology and combining it with an upgraded design that includes a new matte back, three cameras designed to rival the best from Google and Huawei, and an enhanced battery for greater endurance.","phones","https://cdn.dxomark.com/wp-content/uploads/medias/post-54321/iphone-11-pro-max-1.jpg"
2,"Samsung Galaxy S20 Ultra","1399.00","The Samsung Galaxy S20 Ultra is the biggest handset of the Galaxy S20 trio. It has a 6.9-inch display that supports 120Hz but only at 1080p resolution. At the back is situated a huge camera module, housing a grand total of four cameras. The main sensor is 108MP while the periscope sensor can go up to 100x zoom. A 5000mAh battery keeps the lights on.","phones","https://cdn.dxomark.com/wp-content/uploads/medias/post-54321/samsung-galaxy-s20-ultra-1.jpg"
3,"Huawei P40 Pro","999.00","The Huawei P40 Pro is the Chinese manufacturer’s latest high-end smartphone. It features a quad-camera setup that includes a 50MP sensor, 40MP ultra-wide-angle lens, a periscope tele-lens offering 5x optical zoom and a ToF sensor. The P40 Pro is capable of 4K video at 60 fps and offers super slow-motion capture at 7680 fps. The front camera uses a 32MP sensor and offers 4K video at 60 fps as well as slow-motion video at 1080p. The P40 Pro is powered by a Kirin 990 chipset and comes with 8GB of RAM and 256GB of storage. The 6.58-inch OLED display offers a 90Hz refresh rate and a Full HD+ resolution. The battery has a capacity of 4200 mAh and supports 40W wired and 27W wireless charging.","phones","https://cdn.dxomark.com/wp-content/uploads/medias/post-54321/huawei-p40-pro-1.jpg"
4,"Xiaomi Mi 10 Pro","999.00","The Xiaomi Mi 10 Pro is the Chinese manufacturer’s brand-new high-end device, offering premium specs all around, including Qualcomm’s new top-end Snapdragon 865 chipset and a 6.67-inch AMOLED display with 90Hz refresh rate. The camera is a close relative of the Mi CC9 Pro Premium Edition, which achieved the highest DXOMARK Camera score of all devices tested to date. The Mi 10 Pro’s camera features a large 1/1.33-inch 108MP sensor that produces 27MP images and combines four pixels into one to deliver a 1.6μm pixel size. The primary camera is supported by a 20MP ultra-wide-angle shooter, a 12MP portrait camera, and an 8MP telephoto camera. The latter offers 2x magnification compared to the primary camera and features a dual-pixel AF system. The Mi 10 Pro’s video mode can record 8K video at 30 frames per second or 4K footage at up to 60 frames per second.","phones","https://cdn.dxomark.com/wp-content/uploads/medias/post-54321/xiaomi-mi-10-pro-1.jpg"
"#;
