Vagrant.configure(2) do |machine|
  machine.vm.box = "debian/buster64"
  machine.vm.network "private_network", ip: "192.168.77.88"
  machine.ssh.forward_agent = true

  # machine.vm.provision "ansible" do |local|
  #   local.playbook = "playbooks/local.yml"
  # end

  # machine.vm.provision "ansible" do |base|
  #   base.playbook = "playbooks/base.yml"
  #   base.become = true
  #   base.become_user = "root"
  # end

  machine.vm.provision "ansible" do |python|
    python.playbook = "playbooks/python.yml"
  end
end