/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::types;

/// CreateChatCompletionResponseChoicesInnerLogprobs : Log probability information for the choice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateChatCompletionResponseChoicesInnerLogprobs {
    /// A list of message content tokens with log probability information.
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<Vec<types::ChatCompletionTokenLogprob>>,
}

impl CreateChatCompletionResponseChoicesInnerLogprobs {
    /// Log probability information for the choice.
    pub fn new(
        content: Option<Vec<types::ChatCompletionTokenLogprob>>,
    ) -> CreateChatCompletionResponseChoicesInnerLogprobs {
        CreateChatCompletionResponseChoicesInnerLogprobs { content }
    }
}
